### ISSUE TITLE
Create reservation resource transformer for REST API version 1

### ISSUE THREAD

**Issue by cyrildewit** [KA-Huis/space-management#117]
## Description

New REST API endpoints will be created in the following week(s). One common implementation that's needed, before these tickets can be picked up is the `ReservationResource` resource.

## Acceptance criteria

- A reservation resource class is available.
- The reservation resource data contract is validated by tests.

### Tasks

- [x] Create/Extend API resource `ReservationResource` in `App\API\V1\Http\Resources` to transform the Eloquent model
- [x] Create feature test to assert the data contract of the `ReservationResource` resource

#### `ReservationResource` resource

```yml
  schemas:
    Reservation:
      type: object
      properties:
        id:
          type: integer
          format: bigint20
        starts_at:
          type: string
          format: date-time
        ends_at:
          type: string
          format: date-time
        space_id:
          type: integer
          format: bigint20
        group_id:
          type: integer
          format: bigint20
        created_by_user_id:
          type: integer
          format: bigint20
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - starts_at
        - ends_at
        - created_by_user_id
```
