### ISSUE TITLE
Create space resource transformer for REST API version 1

### ISSUE THREAD

**Issue by cyrildewit** [KA-Huis/space-management#99]
## Description

New REST API endpoints will be created in the following week(s). One common implementation that's needed, before these tickets can be picked up is the `SpaceResource` resource.

## Acceptance criteria

- A space resource class is available.
- The space resource data contract is validated by tests.

### Tasks

- [x] Create/Extend API resource `SpaceResource` in `App\API\V1\Http\Resources` to transform the Eloquent model
- [x] Create feature test to assert the data contract of the `SpaceResource` resource

#### `SpaceResource` resource

```yml
  schemas:
    Space:
      type: object
      properties:
        id:
          type: integer
          format: bigint20
        name:
          type: string
        description:
          type: string
        is_open_for_reservations:
          type: boolean
        created_at:
          type: string
        updated_at:
          type: string
      required:
        - id
        - name
        - is_open_for_reservations
```
